# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{less_simple}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Angilly"]
  s.date = %q{2011-01-10}
  s.description = %q{}
  s.email = %q{ryan@angilly.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "less_simple.gemspec",
     "lib/less_simple.rb",
     "test/functional/test_helper.rb",
     "test/test_helper.rb",
     "test/unit/en.yml",
     "test/unit/test_helper.rb",
     "test/unit/test_less_simple.rb"
  ]
  s.homepage = %q{http://github.com/ryana/less_simple}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Adds default interpolation values to the Simple backend for I18n}
  s.test_files = [
    "test/functional/test_helper.rb",
     "test/test_helper.rb",
     "test/unit/test_helper.rb",
     "test/unit/test_less_simple.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 2.3.5"])
      s.add_development_dependency(%q<shoulda>, ["= 2.11.0"])
      s.add_development_dependency(%q<mocha>, ["= 0.9.8"])
      s.add_development_dependency(%q<factory_girl>, ["= 1.3.1"])
      s.add_development_dependency(%q<ruby-debug>, ["= 0.10.3"])
    else
      s.add_dependency(%q<activesupport>, ["~> 2.3.5"])
      s.add_dependency(%q<shoulda>, ["= 2.11.0"])
      s.add_dependency(%q<mocha>, ["= 0.9.8"])
      s.add_dependency(%q<factory_girl>, ["= 1.3.1"])
      s.add_dependency(%q<ruby-debug>, ["= 0.10.3"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 2.3.5"])
    s.add_dependency(%q<shoulda>, ["= 2.11.0"])
    s.add_dependency(%q<mocha>, ["= 0.9.8"])
    s.add_dependency(%q<factory_girl>, ["= 1.3.1"])
    s.add_dependency(%q<ruby-debug>, ["= 0.10.3"])
  end
end

